apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: livekit-server-keys
  namespace: livekit
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: livekit-server-keys
    template:
      type: Opaque
      data:
        keys.yaml: |
          {{ .api_key }}: {{ .api_secret }}
  data:
    - secretKey: api_key
      remoteRef:
        key: livekit-api-key-dev
    - secretKey: api_secret
      remoteRef:
        key: livekit-api-secret-dev
