apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-secret-livekit.yaml

patches:
  - target:
      kind: ClusterSecretStore
      name: gcp-secret-manager
    patch: |-
      - op: replace
        path: /spec/provider/gcpsm/projectID
        value: lt-ai-roleplay-dev
