apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This directory contains Helm values files for LiveKit Server
# These are referenced by ArgoCD Application definitions

configMapGenerator:
  - name: livekit-values-common
    files:
      - values.yaml
