apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: turn-tls-cert
  namespace: livekit
spec:
  secretName: turn-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - turn.dev.levtech.org
