apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate-turn.yaml

patches:
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: admin@levtech.org
  - target:
      kind: ClusterIssuer
      name: letsencrypt-staging
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: admin@levtech.org
