apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livekit-ingress
  namespace: livekit
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: livekit-ip-dev
    networking.gke.io/managed-certificates: livekit-cert-dev
    networking.gke.io/v1beta1.FrontendConfig: livekit-frontend-config
spec:
  defaultBackend:
    service:
      name: livekit-livekit-server
      port:
        number: 7880
  rules:
    - host: livekit.dev.levtech.org
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: livekit-livekit-server
                port:
                  number: 7880
