apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: livekit-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  sources:
    # Git repository with values files
    - repoURL: https://github.com/lv-levtech/livekit-gke.git
      targetRevision: main
      ref: values
    # Helm Chart from LiveKit
    - repoURL: https://helm.livekit.io
      chart: livekit-server
      targetRevision: "1.9.0"
      helm:
        releaseName: livekit
        valueFiles:
          - $values/k8s/livekit-server/base/values.yaml
          - $values/k8s/livekit-server/overlays/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: livekit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
